version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:8000"
    environment:
      - ENV=production
    restart: always
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000